### ISSUE TITLE
Possible to jailbreak on A11 after restore from iOS 15 to 14.8 ??

### ISSUE THREAD

**Issue by TherealXmeD** [Arna13/sunst0rm-guide#6]
Hello.

I was able to downgrade my iPhone X to from iOS 15.2 beta 1 to iOS 14.8 thanks to this great tool. But how can I jailbreak the device with checkra1n since I need to use boot.sh every time the device reboots.

**Comment by Arna13** [comment]
Checkra1n is not compatible, the only way to get jailbreak right now is on iOS 14.0-14.3 with Tairune, closing the issue.
